# Generated by Django 3.1.3 on 2020-12-30 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
